### ISSUE TITLE
blog / canal no slack

### ISSUE THREAD

**Issue by hernandev** [golangbr/golangbr#1]
Olá, existe algum canal de comunicação sobre go? 

Acho interessante um blog onde possamos postar artigos, pode ser feito com hugo por exemplo.

Criei um canal no slack, mas não sei se já existe algo desse tipo.

**Comment by crgimenes** [comment]
O canal que costumo usar é esse https://invite.slack.golangbridge.org

**Comment by hernandev** [comment]
Interessante, não conhecia esse slack!
A ideia é termos canais brasileiros...

**Comment by crgimenes** [comment]
Então, ai tem vários canais inclusive o #brasil e o #saopaulo
o pessoal do Rio ta usando Telegram

**Comment by crgimenes** [comment]
https://gophers.slack.com/archives/brazil

**Comment by hernandev** [comment]
show, entrarei entao
